version: '3.8'  # pode remover se quiser, conforme aviso do Compose

services:
  PFS-DB-CORE:
    image: postgres:17
    container_name: PFS-DB-CORE 
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PFS-DB-CORE
    ports:
      - "5432:5432"
    volumes:
      - ./DB/data/core:/var/lib/postgresql/data
      - ./DB/dump-core-PFS-CORE.dump:/restore/dump-core-PFS-CORE.dump
      - ./DB/restore-core.sh:/docker-entrypoint-initdb.d/restore-core.sh
    restart: unless-stopped
    networks:
      - pfs-network

  PFS-DB-MG:
    image: postgres:17
    container_name: PFS-DB-MG
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PFS-DB-MG
    ports:
      - "5433:5432"
    volumes:
      - ./DB/data/mg:/var/lib/postgresql/data
      - ./DB/dump-core-PFS-MG.dump:/restore/dump-core-PFS-MG.dump
      - ./DB/restore-mg.sh:/docker-entrypoint-initdb.d/restore-mg.sh
    restart: unless-stopped
    networks:
      - pfs-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - pfs-network

  api:
    build:
      context: ./backend/net8.0
      dockerfile: API/Dockerfile
    ports:
      - "3190:3190"
    depends_on:
      - PFS-DB-CORE
      - PFS-DB-MG
    environment:
      ASPNETCORE_URLS: http://+:3190
      ConnectionStringCore: Host=PFS-DB-CORE;Port=5432;Database=PFS-DB-CORE;Username=postgres;Password=admin
      ConnectionStringMG: Host=PFS-DB-MG;Port=5432;Database=PFS-DB-MG;Username=postgres;Password=admin
    restart: unless-stopped
    networks:
      - pfs-network

networks:
  pfs-network:
    external: true